apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wsa18p9qs-dotnet-basic
  janus-idp.io/tekton: wsa18p9qs-dotnet-basic
  backstage.io/kubernetes-id: wsa18p9qs-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wsa18p9qs-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
