apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wsa18p9qs-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wsa18p9qs-dotnet-basic 
  name: wsa18p9qs-dotnet-basic
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wsa18p9qs-dotnet-basic 
